patrol_node:
  ros__parameters:
    # 要加.0 否则会识别为 int 类型
    initial_point: [0.0, 0.0, 0.0]
    target_points:
      [
        0.0,
        0.0,
        0.0,
        1.0,
        2.0,
        3.14,
        -4.5,
        1.5,
        1.57,
        -8.0,
        -5.0,
        1.57,
        1.0,
        -5.0,
        3.14,
      ]
    # 自动巡检目标处图像路径
    image_save_path: "/home/changli/Documents/ROS/YuXiangROS/Chap7/Navigation_ws/images"
